### PR TITLE
fix using skip_packages arg

### LINKED ISSUE #90: Errors using ament uninstall
Following error happens on osx and trusty (at least) with any set of arguments

```
14:34:37 deanna /Users/deanna/ros2_ws
$ src-master/ament/ament_tools/scripts/ament.py uninstall --only-package rmw_connext_cpp
Traceback (most recent call last):
  File "src-master/ament/ament_tools/scripts/ament.py", line 149, in <module>
    sys.exit(main() or 0)
  File "/Users/deanna/ros2_ws/src-master/ament/ament_tools/ament_tools/commands/ament.py", line 88, in main
    rc = args.main(args)
  File "/Users/deanna/ros2_ws/src-master/ament/ament_tools/ament_tools/verbs/uninstall/cli.py", line 90, in main
    print_topological_order(opts, packages)
  File "/Users/deanna/ros2_ws/src-master/ament/ament_tools/ament_tools/verbs/build/cli.py", line 172, in print_topological_order
    opts.skip_packages = opts.skip_packages or []
AttributeError: 'Namespace' object has no attribute 'skip_packages'
```

Think the cause is similar to https://github.com/ament/ament_tools/issues/84 but haven't looked into it yet

### PR DESCRIPTION
**Pull request by dirk-thomas**
Fixes #90.

### CODE REVIEW

**Comment by dirk-thomas** [comment]
Fixed regression in f0a70e05332d10df07eadb17ff8fadd5d745a435.
