### ISSUE TITLE
uninstall verb fails

### ISSUE THREAD

**Issue by dhood** [ament/ament_tools#122]
broken since https://github.com/ament/ament_tools/pull/114
```
dhood@osrf-esteve:~/ros2_test_ws [ros2_test_ws]$ ament uninstall
# Topological order
Traceback (most recent call last):
  File "/home/dhood/ros2_ws/install_isolated/ament_tools/bin/ament", line 9, in <module>
    load_entry_point('ament-tools', 'console_scripts', 'ament')()
  File "/home/dhood/ros2_ws/build_isolated/ament_tools/ament_tools/commands/ament.py", line 88, in main
    rc = args.main(args)
  File "/home/dhood/ros2_ws/build_isolated/ament_tools/ament_tools/verbs/uninstall/cli.py", line 91, in main
    print_topological_order(opts, packages)
  File "/home/dhood/ros2_ws/build_isolated/ament_tools/ament_tools/verbs/build/cli.py", line 240, in print_topological_order
    if pkg_name in opts.skip_packages:
AttributeError: 'Namespace' object has no attribute 'skip_packages'
```

**Comment by dirk-thomas** [comment]
See #123.
